name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master  # Auf den Branch achten

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-demo:latest

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-demo:latest|g" k8s/deployment.yaml
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -am "Update Docker image version"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


    - name: Trigger ArgoCD Sync
      run: |
        curl -X POST https://dbb6-79-247-139-99.ngrok-free.app/api/v1/applications/FastTest/sync \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_AUTH_TOKEN }}"
