name: Build and Deploy with Dynamic Tag

on:
  push:
    branches:
      - master  # Oder 'master', je nachdem welcher Branch genutzt wird

permissions:
  contents: write  # Erlaubt dem Workflow, Änderungen ins Repo zu pushen

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set Docker Tag (Commit Hash)
      id: vars
      run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image with Dynamic Tag
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/arm64
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-demo:${{ env.IMAGE_TAG }}

    - name: Update Kubernetes Deployment with New Image Tag
      run: |
        sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-demo:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        if [[ -n $(git status --porcelain) ]]; then
          git commit -am "Update image tag to ${{ env.IMAGE_TAG }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        else
          echo "No changes to commit."
        fi
